apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    metadata:
      labels:
        app: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job
          image: registry.cn-hangzhou.aliyuncs.com/jin82/k8s-job