apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
data:
  REDIS_HOST: svc-redis
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rest
data:
  APP_CONTENT: This is ConfigMap Content!

