apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-rest
  labels:
    type: biz
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: rest
          image: registry.cn-hangzhou.aliyuncs.com/jin82/k8s-rest:1.0
          imagePullPolicy: Always
          env:
            - name: APP_SERVER_PORT
              value: "8080"
            - name: APP_CONTENT
              valueFrom:
                configMapKeyRef:
                  key: APP_CONTENT
                  name: cm-rest
          envFrom:
            - prefix: MIDDLEWARE_
              configMapRef:
                name: cm-common
          ports:
            - containerPort: 8080
              name: http

