apiVersion: v1
kind: Service
metadata:
  name: svc-np-rest
  labels:
    type: biz
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 30080
  selector:
    app: rest