apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        type: basic
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
            name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis
  labels:
    type: basic
spec:
  ports:
    - port: 6379
      targetPort: tcp
  selector:
    app: redis